export const  Action = {
    AUTH: 'AUTH',
    NOTIFY: 'NOTIFY',
    ACCESS_TOKEN: 'ACCESS_TOKEN',
    R_TOKEN: 'R_TOKEN',
    CART: 'CART',
    EXEL_IMPORT: 'EXEL_IMPORT',
    UPLOAD_STATUS: 'UPLOAD_STATUS',
    MENU_BOX: 'MENU_BOX',
    USER: 'USER',
    SELECTED_COVERS: 'SELECTED_COVERS',
    SELECTED_COVERS_ID: 'SELECTED_COVERS_ID',
    SEARCH: 'SEARCH',

}